name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t hungluu1111/mcq-paraphraser:latest .
      - name: push image to docker hub
        run: |
          docker login -u hungluu1111 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push hungluu1111/mcq-paraphraser:latest
